fyp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from core import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('', include('authentication.urls')),
    path('shop/', include('shop.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }), ]

shop/urls.py
from django.urls import path, include
from .views import (
    shop,
    search,
    add_product,
    pro_view,
    add_to_cart,
    Cart,
    remove,
    remove_all,
    product_rating
    # increase_quantity
)
from user_profile import views

urlpatterns = [
    path('', shop, name='shop'),
    path('search/', search, name='search'),
    path('add/', add_product, name='addproduct'),
    path('product_details/<int:id>', pro_view, name='productview'),
    path('rate-product/<int:id>', product_rating, name='product_rating'),
    path('add-to-cart/<int:id>', add_to_cart, name='addtocart'),
    # path('increase-quantity/<int:id>', increase_quantity, name='increase_quantity'),
    path('cart/', Cart.as_view(), name='cart'),
    path('remove/<int:id>', remove, name='remove'),
    path('remove-all/<int:id>', remove_all, name='remove_all'),
    #user_profile
    path('profile/<int:id>', views.profile, name='profile'),
    path('changepass/', views.change_pass, name='changepass'),
    path('<int:id>/', views.dlt, name='deleteproduct'),
]

shop/models.py
from django.db.models import Avg
from django.conf import settings
from django.db import models
from datetime import datetime

# Create your models here.

CATEGORY_CHOICES = (
                ('', 'Select an option'),
                ('C', 'clothing'), #First one is the value of select option and second is the displayed value in option
                ('E', 'electronics'),
                ('G', 'groceries'),
                ('HA', 'home accessories'),
                )
SUB_CATEGORY_CHOICES = (
    ('', 'Select an option'),
    ('men','men'),
    ('women','women'),
    ('mob','mobile'),
    ('com','computer'),
    ('machine','machinery'),
    ('tv','television'),
    ('furn','furniture'),
    ('kitc','kitchen'),
)

class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    product_name = models.CharField(max_length=60)
    description = models.CharField(max_length=400)
    pub_date = models.DateTimeField(auto_now_add=True)
    category = models.CharField(max_length=25, choices=CATEGORY_CHOICES)
    sub_category = models.CharField(max_length=25, choices=SUB_CATEGORY_CHOICES, blank=True, null=True)
    price = models.IntegerField(default=0)
    bulk_quantity = models.IntegerField(default=0)
    bulk_price = models.IntegerField(default=0)
    seller_contact = models.CharField(max_length=11)

    def __str__(self):
        return f"{self.id}: {self.product_name}"

    def num_of_reviews(self):
        return self.prorating_set.count()

    def average_rating(self):
        return self.prorating_set.aggregate(Avg('rate'))['rate__avg']

class Pimage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    image = models.ImageField(upload_to='shop/images/')

    def __str__(self):
        return self.product.product_name

class ProRating(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    review = models.CharField(max_length=250)
    rate = models.IntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} of {self.item.product_name}"
    
    def total_price(self):
        return self.quantity*self.item.price


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # or_items = models.ForeignKey(OrderItem, on_delete=models.CASCADE, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    bill_address = models.ForeignKey('PlacedOrder', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    recieved = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    def cart_total(self):
        total = 0 
        for orders in self.items.all():
            total += orders.total_price()
        return total
    
COUNTRY = (
    ('', 'Select Country'),
    ('1', 'Pakistan')
)
CITY = (
    ('', 'Select City'),
    ('1', 'Hyderabad')
)
    
class PlacedOrder(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE, blank=True, null=True)
    contact = models.CharField(max_length=11)
    address = models.TextField(max_length=150)
    address2 = models.TextField(max_length=150)
    country = models.CharField(max_length=15, choices=COUNTRY, default='Pakistan')
    city = models.CharField(max_length=15, choices=CITY, default="Hyderabad")
    zip_code = models.CharField(max_length=8)

    def __str__(self):
        return self.user.username

shop/forms.py
from django import forms 
from .models import Product, PlacedOrder, Pimage, ProRating



class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_name', 'category', 'sub_category', 'bulk_quantity', 'bulk_price', 'price', 'description', 'seller_contact']
        widgets = {
            'product_name': forms.TextInput(attrs={'class': 'form-control is-valid', 'required': True}),
            'description': forms.Textarea(attrs={'class': 'form-control is-valid', 'rows': 3}),
            'category': forms.Select(attrs={'class': 'form-select is-valid'}),
            'sub_category': forms.Select(attrs={'class': 'form-select is-valid'}),
            'price': forms.TextInput(attrs={'type': 'number', 'class': 'form-control is-valid'}),
            'bulk_quantity': forms.TextInput(attrs={'type': 'number', 'class': 'form-control is-valid'}),
            'bulk_price': forms.TextInput(attrs={'type': 'number', 'class': 'form-control is-valid'}),  
            'seller_contact': forms.NumberInput(attrs={'class': 'form-control is-valid'}),  
            'pub_date': forms.TextInput(attrs={'type': 'date', 'class': 'form-control is-valid'})
        }
        labels = {'bulk_quantity': 'Bulk Products(if any)', 'bulk_price': 'Bulk Products Price(if any)', 'sub_category': 'Sub-category(if any)'}

class RateForm(forms.ModelForm):
    class Meta:
        model = ProRating
        fields = ['review', 'rate']

class PimgForm(forms.ModelForm):
    # images = forms.FileInput(attrs={'type': 'file', 'class': 'form-control', 'multiple': True})
    class Meta:
        model = Pimage
        fields = ['image']
        widgets = {
            'image': forms.FileInput(attrs={'type': 'file', 'class': 'form-control', 'multiple': True, 'required': True})
        }
        labels = {'image': 'Add Images(High quality recommended)'}

class ConfirmOrderForm(forms.ModelForm):
    class Meta:
        model = PlacedOrder
        fields = ['contact', 'address', 'address2', 'country', 'city', 'zip_code']
        widgets = {
            'contact': forms.NumberInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control', 'placeholder':"1234 Main St"}),
            'address2': forms.TextInput(attrs={'class': 'form-control', 'placeholder':"1234 Main St"}),
            'country': forms.Select(attrs={'class': 'form-control', 'required': False, 'value': 'Pakistan'}),
            'city': forms.Select(attrs={'class': 'form-control', 'required': False, 'value': 'Hyderabad'}),
            'zip_code': forms.NumberInput(attrs={'class': 'form-control'}),
        }

shop/views.py
from django.shortcuts import render, HttpResponseRedirect, redirect
from .models import Order, OrderItem, Product, PlacedOrder, Pimage, ProRating
from .forms import AddProductForm, ConfirmOrderForm, PimgForm, RateForm
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.views.generic import View 
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q


# Create your views here.

# to show the products on the shop page
def shop(request):
    if request.user.is_authenticated:
        products = Product.objects.all().order_by('-id')
        clothing = Product.objects.filter(category='C').order_by('-id')
        clothing_men = Product.objects.filter(category='C', sub_category='men').order_by('-id')
        clothing_men = Product.objects.filter(category='C', sub_category='men').order_by('-id')
        clothing_women = Product.objects.filter(category='C', sub_category='women').order_by('-id')
        electronics = Product.objects.filter(category='E').order_by('-id')
        groceries = Product.objects.filter(category='G').order_by('-id')
        home_accessories = Product.objects.filter(category='HA').order_by('-id')
        context = {
            'shop': 'active', 
            'products': products, 
            'clothing': clothing, 
            'clothing_men': clothing_men, 
            'clothing_women': clothing_women,
            'electronics': electronics, 
            'groceries': groceries, 
            'home_accessories': home_accessories
            }
        return render(request, 'shop/shop.html', context) 
    else:
        return HttpResponseRedirect('/login/')


# to search a particular product by product name
def search(request):
    if request.user.is_authenticated:
        q = request.GET['q']
        products = Product.objects.filter(
            Q(product_name__icontains=q) | Q(price__icontains=q)).order_by('-id')
        # search_result = [item for item in products if searchMatch(q, item)]
        if len(products) == 0:
            messages.add_message(request, messages.ERROR, 'Nothing to show!')
        context = {'shop': 'active', 'products': products}
        return render(request, 'shop/search.html', context) 
    else:
        return HttpResponseRedirect('/login/')

# to add products on the shop
def add_product(request):
    url = request.META.get('HTTP_REFERER')
    if request.user.is_authenticated:
        img_form = PimgForm()
        if request.method == 'POST':
            add_form = AddProductForm(request.POST)
            files = request.FILES.getlist('image')
            if add_form.is_valid():
                product = add_form.save(commit=False)
                product.user = request.user
                product.save()
                for img in files:
                    img = Pimage.objects.create(product=product, image=img)
                add_form = AddProductForm()
                HttpResponseRedirect(url)
                messages.add_message(request, messages.SUCCESS, 'Product added successfully!')
        else:
            add_form = AddProductForm()
            img_form = PimgForm()
        context = {'addForm': add_form, 'imgForm': img_form}
        return render(request, 'shop/addproduct.html', context)
    else:
        return HttpResponseRedirect('/login/')

# to view the details of a single product
def pro_view(request, id):
    # user = User.objects.get(pk=id)
    product = Product.objects.get(pk=id)
    product_rating = ProRating.objects.filter(product_id=id).order_by('-id')
    similar_prods = Product.objects.filter(category=product.category).exclude(id=id)[:3]
    context = {'product': product, 'similar_products': similar_prods, 'productrating': product_rating}
    return render(request, 'shop/proview.html', context)

# to rate a product on a scale of 1-5 stars
def product_rating(request, id):
    url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        form = RateForm(request.POST)
        if form.is_valid():
            rating = ProRating()
            rating.user = request.user
            rating.product_id = id
            rating.review = form.cleaned_data['review']
            rating.rate = form.cleaned_data['rate']
            rating.save()
    else:
        form = RateForm()
    return HttpResponseRedirect(url)

# to add items into the cart
def add_to_cart(request, id):
    item = get_object_or_404(Product, id=id)
    order_item, created = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__id=item.id).exists():
            order_item.quantity += 1
            order_item.save()
        else:
            order.items.add(order_item)
    else:
        order = Order.objects.create(user=request.user)
        order.items.add(order_item)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

# to remove a single item from the cart
def remove(request, id):
    item = get_object_or_404(Product, id=id)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__id=item.id).exists():
            order_item = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)[0]
            if order_item.quantity >= 2:
                order_item.quantity -= 1
                order_item.save()
            else:
                order_item.delete()
        else:
            return redirect('/shop/cart/', id=id)
    else:
        return redirect('/shop/cart/', id=id)
    return redirect('/shop/cart/', id=id)

# to remove all items from the cart
def remove_all(request, id):
    item = get_object_or_404(Product, id=id)
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__id=item.id).exists():
            order_item = OrderItem.objects.get_or_create(item=item, user=request.user, ordered=False)[0]
            order_item.delete()
        if order_item.quantity <= 1:
            order.delete()
        else:
            return redirect('/shop/cart/', id=id)
    else:
        return redirect('/shop/cart/', id=id)
    return redirect('/shop/cart/', id=id)

    
# to show the products added into cart and placing an order
class Cart(View):
    def get(self, *args, **kwargs):
        form = ConfirmOrderForm()
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                    'cart': order, 'form': form,
                    }
            return render(self.request, 'shop/cart.html', context)
        except ObjectDoesNotExist:
            order = OrderItem.objects.all()
            # messages.add_message(self.request, messages.SUCCESS, 'Product added successfully!)
            context = {
                    'cart': order, 'form': form,
                    }
            return render(self.request, 'shop/cart.html', context)
        
    def post(self, *args, **kwargs):    
        form = ConfirmOrderForm(self.request.POST)
        order = Order.objects.get(user=self.request.user, ordered=False)
        ORDERED_ITEMS = OrderItem.objects.filter(user=self.request.user)
        if form.is_valid():
            contact = form.cleaned_data.get('contact')
            address = form.cleaned_data.get('address')
            address2 = form.cleaned_data.get('address2')
            country = form.cleaned_data.get('country')
            city = form.cleaned_data.get('city')
            zip_code = form.cleaned_data.get('zip_code')
            placed_order = PlacedOrder(
                user=self.request.user,
                contact=contact,
                address=address,
                address2=address2,
                country=country,
                city=city,
                zip_code=zip_code
            )
            placed_order.save()
            order.bill_address = placed_order
            order.ordered = True
            ORDERED_ITEMS.update(ordered=True)
            order.save()
            messages.add_message(self.request, messages.SUCCESS, 'Order placed successfully!')
        return redirect('/shop/cart/')
            

templates/shop/addproduct.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sasta Bazaar - Add Product{% endblock title %}
{% block head %}
<style>
  #add {
    background: linear-gradient(rgba(255,255,255,.4), rgba(255,255,255,.4)), url("/static/images/2483946.jpg");
    background-size: cover;
  }

  .errorlist {
    color: red;
    height: 20px;
    list-style: none;
  }
</style>
{% endblock head %}
{% block content %}
{% if messages %}
{% for msg in messages %}
<div style="position: absolute; top: 85px; width: 100vw;" {% if msg.tags %} class="alert alert-{{msg.tags}} alert-dismissible fade show" {% endif %} role="alert">
    {{msg}} <strong>{{request.user.get_full_name}}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
    {% endfor %}
{% endif %}

    <div class="container-fluid p-2" id="add">
    
      <h1 class="text-center">You can add your own product here!</h1>

      <div class="col-sm-6 col-md-6 col-lg-6 m-auto p-2">
        <form action="" method="post" novalidate enctype="multipart/form-data"> {% csrf_token %}
            {% for field in addForm %}
                <p>{{field.label_tag}} {{field}}</p>
                <p>{{field.errors}}</p>
            {% endfor %}
            {{imgForm.management_form}}
            {% for form in imgForm %}
              <p>{{form.label_tag}} {{form}}</p>
            {% endfor %}
            <button type="submit" class="btn btn-success mt-2">Add Now</button>
        </form>
      </div>

</div>
{% endblock content %}

templates/shop/cart.html
{% extends 'base.html' %}
{% load static %}
{% load cart_template_tags %}
{% block title %}Sasta Bazaar - Cart{% endblock title %}
{% block head %}
{% comment %} <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
<link rel="stylesheet" href="node_modules/mdbootstrap/css/bootstrap.min.css">
<link rel="stylesheet" href="node_modules/mdbootstrap/css/mdb.min.css">
<link rel="stylesheet" href="node_modules/mdbootstrap/css/style.css"> {% endcomment %}
<style>
    #cart {
        min-height: 500px;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
</style>
{% endblock head %}
{% block content %}
<section id="cart">
  {% if messages %}
  {% for msg in messages %}
  <div style="position: absolute; top: 85px; width: 100vw;" {% if msg.tags %} class="alert alert-{{msg.tags}} alert-dismissible fade show" {% endif %} role="alert">
      {{msg}} 
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
      {% endfor %}
  {% endif %}
    
  <div class="row">
    
    <div class="col-sm-7 mt-4">
      {% for order in cart.items.all %}
    <div class="card rounded-3 mb-4">
        <div class="card-body p-4">
            <div class="row d-flex justify-content-between align-items-center">             
                <div class="col-md-2 col-lg-2 col-xl-2">
                <a href="{% url 'productview' order.item.id %}">
                  {% with order.item.pimage_set.all|first as photo %}
                <img
                    src="{{photo.image.url}}"
                    class="img-thumbnail rounded-3" alt="Cotton T-shirt">
                </a>
                {% endwith %}
                                
                </div>
            <div class="col-md-4 col-lg-4 col-xl-4">
              <p class="lead fw-norma mb-2"><b>{{order.item.product_name | slice:":20"}}</b></p>
              <h6 class="mb-0" style="font-size: 80%;"><b>Category: </b>{{order.item.get_category_display | upper }}</h6>
              <p><span class="text-muted" style="font-size: 80%;">{{order.item.description | slice:":35"}}...</p>
            </div>
            <div class="col-md-2 col-lg-2 col-xl-2 d-flex" style="font-size: 70%;">
            <form action="{% url 'remove' order.item.id %}" method="post">{% csrf_token %}
              <button class="btn btn-link" style="font-size: 80%;">
                <i class="fas fa-minus"></i>
              </button>
            </form>

                <p style="font-size: 140%;">{{order.quantity}}</p>
            <form action="{% url 'addtocart' order.item.id %}" method="post">{% csrf_token %}
              <button class="btn btn-link" style="font-size: 80%;">
                <i class="fas fa-plus"></i>
              </button>
            </form>
            </div>
            <div class="col-md-3 col-lg-2 col-xl-2 mb-2">
              <div class="d-block">
                <h6 class="mb-1" style="font-size: 90%;">Rs.{{order.item.price}}</h6>
                <h6 class="mb-0" style="font-size: 90%;">Total Price Rs.{{order.total_price}}</h6>
              </div>
            </div>
            
            <div class="col-md-2 col-lg-2 col-xl-2 text-end">
              
                <form action="{% url 'remove_all' order.item.id %}" method="post" class="text-center"> {% csrf_token %}
                    <button class="btn btn-sm btn-danger" type='submit'><i class="fas fa-trash-alt"></i></button>
                </form>
              
              </div>
          </div>
        </div>
      </div>

        {% endfor %}
        {% if cart.cart_total >= 1 %}
        <table class="table table-dark table-hover mx-2">
          <tr>
            <td>Cart Total -</td>
            <td>Rs.{{cart.cart_total}}.00</td>
          </tr>
        </table>
        {% endif %}
      </div>

    {% if cart.cart_total >= 1 %}
    <div class="col-sm-5 mt-4">

      {% comment %} <form action="" method="post"> {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Place Order">
      </form> {% endcomment %}

      <form class="row g-3 px-2" method="POST"> {% csrf_token %}
        <div class="col-sm-12">
          <label for="id_contact" class="form-label">{{form.contact.label_tag}}</label>
          {{form.contact}}
        </div>
        
        <div class="col-12">
          <label for="id_address" class="form-label">{{form.address.label_tag}}</label>
          {{form.address}}
        </div>
        <div class="col-12">
          <label for="id_address2" class="form-label">{{form.address2.label_tag}}</label>
          {{form.address2}}
        </div>
        <div class="col-sm-12">
          <label for="id_country" class="form-label">{{form.country.label_tag}}</label>
          {{form.country}}
        </div>
        <div class="col-sm-7">
          <label for="id_city" class="form-label">{{form.city.label_tag}}</label>
          {{form.city}}
        </div>
        
        <div class="col-sm-5">
          <label for="id_zip" class="form-label">{{form.zip_code.label_tag}}</label>
          {{form.zip_code}}
        </div>
        <div class="col-12">
          <div class="form-check">
            <input class="form-check-input" type="checkbox" id="gridCheck">
            <label class="form-check-label" for="gridCheck">
              Cash on delivery* 
            </label>
          </div>
        </div>
        <div class="col-12 mb-2">
          <div class="d-grid gap-2">
            <button type="submit" class="btn btn-dark">Place Order</button>  
          </div>
        </div>
      </form>
    </div>
  </div>
 

  {% else %}
  <div class="container m-auto text-center">
    <h3 class="text-center m-auto">Your cart is empty!</h3>
    <a href="{% url 'shop' %}" class="btn btn-primary btn-sm">Continue Shopping</a>
  </div>
  {% endif %}
  
  {% comment %} <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}

    {% for field in form %}
        <p>{{field.label_tag}} {{field}}</p>
        <p>{{field.errors}}</p>
    {% endfor %}
    <input type="submit" value="submit">
  </form>  {% endcomment %}
  {% if ordered %}
  {% for it in ordered.items.all %}
    <div>{{it}}</div>
  {% endfor %} 
  {% endif %}
  
  
</section>
    {% endblock content %}

templates/shop/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sasta Bazaar - Shop{% endblock title %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/shop/swiper.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop/shop.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop/media.css' %}">
{% endblock head %}
{% block cat_tab %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Categories
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      <li><a class="dropdown-item" href="#all-products">All Products</a></li>
      <li><a class="dropdown-item" href="#clothing">Clothing</a></li>
      <li><a class="dropdown-item" href="#electronics">Electronics</a></li>
      <li><a class="dropdown-item" href="#groceries">Groceries</a></li>
      <li><hr class="dropdown-divider"></li>
      <li><a class="dropdown-item" href="#">Something else here</a></li>
    </ul>
</li>
{% endblock cat_tab %}
{% block content %}
<section id="shop">
    

    <div class="container mt-2">
        <div class="d-grid gap-2">
            <a class="btn btn-outline-success" type="button" href="{% url 'addproduct' %}">Add your Product+</a>
        </div>
    </div>

    <div class="product-box">

        <h1 class="shop-heading mt-4" id="all-products">Search Results</h1>
        {% if messages %}
    {% for msg in messages %}
    <div style="width: 100vw;" class="text-center p-5">
        {{msg}}
    </div>
        {% endfor %}
    {% endif %}

        <div class="slider-container swiper">
            <div class="card-wrapper">
                <div class="slide-content">
                    <div class="card-wrapper swiper-wrapper">
                        {% for item in products %}
                        <div class="card swiper-slide" style="width: 18rem;">
                            {% with item.pimage_set.all|first as photo %}
                                <img src="{{photo.image.url}}" class="card-img-top" alt="...">
                            {% endwith %}
                            <div class="card-body">
                              <p class="card-title text-center">{{item.product_name}}</p>
                              <p class="card-text"><b>Description</b> {{item.description | slice:":40"}}...</p>
                              <p class="card-text"><b>Rs.</b> {{item.price}}</p>
                              <div class="d-flex">
                                  {% comment %} <a href="#"><button class="btn btn-sm btn-warning">Add to Cart</button></a> {% endcomment %}
                                  <form action="{% url 'addtocart' item.id %}" method="post"> {% csrf_token %}
                                      <button class="btn btn-sm btn-warning" type='submit'>Add to Cart</button>
                                  </form>
                                  <a href="{% url 'productview' item.id %}"><button class="btn btn-sm btn-info mx-2">View Details</button></a>
                              </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
    
            <div class="swiper-button-next swiper-navBtn"></div>
            <div class="swiper-button-prev swiper-navBtn"></div>
            <div class="swiper-pagination"></div>
    
        </div>

    </div>

    </div>




    
    
</section>
{% endblock content %}
{% block js %}
<script src="{% static 'js/shop/swiper.js' %}"></script>
<script src="{% static 'js/shop/shop.js' %}"></script>
{% endblock js %}